---

- name: Check OS version and family
  tags: always
  ansible.builtin.assert:
    that: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version_compare('20', '==')
    msg: "This role can only be run against Ubuntu 20. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."

- name: Check ansible version
  tags: always
  ansible.builtin.assert:
    that: ansible_version.full is version_compare(min_ansible_version, '>=')
    fail_msg: "You must use Ansible {{ min_ansible_version }} or greater"
    success_msg: "This role is running a supported version of ansible {{ ansible_version.full }} >= {{ min_ansible_version }}"

- name: Ensure grub password has been changed
  when:
    - ubtu20cis_set_grub_user_password
    - ubtu20cis_rule_1_4_2
  #  This control should always run as this can pass on unintended issues.
  ansible.builtin.assert:
    that:
      - '"ChangeMe" not in ubtu20cis_bootloader_password_hash'
      - '"grub.pbkdf2.sha512.1000" in ubtu20cis_bootloader_password_hash'
    fail_msg: "The default grub password has not been changed"

- name: "Check password set for connecting user"
  when:
    - ubtu20cis_rule_5_2_4
    - ansible_env.SUDO_USER is defined
  tags: always
  block:
    - name: "Capture current password state of connecting user"
      ansible.builtin.shell: "grep {{ ansible_env.SUDO_USER }} /etc/shadow | awk -F: '{print $2}'"
      changed_when: false
      failed_when: false
      no_log: true
      check_mode: false
      register: ansible_user_password_set

    - name: "Assert that password set for {{ ansible_env.SUDO_USER }} and account not locked"  # noqa: name[template]
      ansible.builtin.assert:
        that: ansible_user_password_set.stdout | length != 0 and ansible_user_password_set.stdout != "!!"
        fail_msg: "You have {{ sudo_password_rule }} enabled but the user = {{ ansible_env.SUDO_USER }} has no password set - It can break access"
        success_msg: "You have a password set for sudo user {{ ansible_env.SUDO_USER }}"
      vars:
        sudo_password_rule: ubtu20cis_rule_5_2_4  # pragma: allowlist secret

- name: Setup rules if container
  when:
    - ansible_connection == 'docker' or ansible_virtualization_type in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
    - container_discovery
    - always
  block:
    - name: Discover and set container variable if required
      ansible.builtin.set_fact:
        system_is_container: true

    - name: Load variable for container
      ansible.builtin.include_vars:
        file: "{{ container_vars_file }}"

    - name: Output if discovered is a container
      when:
        - system_is_container
      ansible.builtin.debug:
        msg: system has been discovered as a container

- name: Import preliminary tasks
  tags:
    - prelim_tasks
    - run_audit
  ansible.builtin.import_tasks:
    file: prelim.yml

- name: Include audit specific variables
  when: run_audit or audit_only or setup_audit
  tags:
    - setup_audit
    - run_audit
  ansible.builtin.include_vars: audit.yml

- name: Include pre-remediation audit tasks
  when: run_audit or audit_only or setup_audit
  tags: run_audit
  ansible.builtin.import_tasks: pre_remediation_audit.yml

- name: Run parse /etc/passwd
  when:
    - ubtu20cis_section5_patch or ubtu20cis_section7_patch
  ansible.builtin.import_tasks:
    file: parse_etc_password.yml

- name: Gather the package facts
  tags: always
  ansible.builtin.package_facts:
    manager: auto

- name: Include section 1 patches
  when:
    - ubtu20cis_section1_patch
  tags: section1
  ansible.builtin.import_tasks:
    file: section_1/main.yml

- name: Include section 2 patches
  when:
    - ubtu20cis_section2_patch
  tags: section2
  ansible.builtin.import_tasks:
    file: section_2/main.yml

- name: Include section 3 patches
  when:
    - ubtu20cis_section3_patch
  tags: section3
  ansible.builtin.import_tasks:
    file: section_3/main.yml

- name: Include section 4 patches
  when:
    - ubtu20cis_section4_patch
  tags: section4
  ansible.builtin.import_tasks:
    file: section_4/main.yml

- name: Include section 5 patches
  when:
    - ubtu20cis_section5_patch
  tags: section5
  ansible.builtin.import_tasks:
    file: section_5/main.yml

- name: Include section 6 patches
  when:
    - ubtu20cis_section6_patch
  tags: section6
  ansible.builtin.import_tasks:
    file: section_6/main.yml

- name: Include section 7 patches
  when:
    - ubtu20cis_section7_patch
  tags: section7
  ansible.builtin.import_tasks:
    file: section_7/main.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Run post remediation tasks
  tags:
    - post_tasks
    - always
  ansible.builtin.import_tasks:
    file: post.yml

- name: Run post audit
  when:
    - run_audit
  ansible.builtin.import_tasks:
    file: post_remediation_audit.yml

- name: Add ansible file showing Benchmark and levels applied
  when: create_benchmark_facts
  tags:
    - always
    - benchmark
  block:
    - name: Create ansible facts directory
      ansible.builtin.file:
        path: "{{ ansible_facts_path }}"
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'

    - name: Create ansible facts file
      ansible.builtin.template:
        src: etc/ansible/compliance_facts.j2
        dest: "{{ ansible_facts_path }}/compliance_facts.fact"
        owner: root
        group: root
        mode: "u-x,go-wx"

- name: Fetch audit files
  when:
    - fetch_audit_output
    - run_audit
  tags: always
  ansible.builtin.import_tasks:
    file: fetch_audit_output.yml

- name: Show Audit Summary
  when:
    - run_audit
  tags: run_audit
  ansible.builtin.debug:
    msg: "{{ audit_results.split('\n') }}"

- name: Output Warning count and control IDs affected
  tags: always
  ansible.builtin.debug:
    msg: "You have {{ warn_count }} warning(s) that require investigating that are related to the following benchmark ID(s) {{ warn_control_list }}"
