---

- name: Gather the package facts
  tags: always
  ansible.builtin.package_facts:
    manager: auto

- name: "PRELIM | Section 1.1 | Create list of mount points"
  tags: always
  ansible.builtin.set_fact:
    prelim_mount_names: "{{ ansible_facts.mounts | map(attribute='mount') | list }}"

- name: PRELIM | Capture tmp mount type | discover mount tmp type
  when:
    - "'/tmp' in prelim_mount_names"
    - ubtu20cis_rule_1_1_2_1_1 or ubtu20cis_rule_1_1_2_1_2 or ubtu20cis_rule_1_1_2_1_3 or ubtu20cis_rule_1_1_2_1_4
  tags: always
  block:
    - name: PRELIM | Capture tmp mount type | discover mount tmp type
      ansible.builtin.command: systemctl is-enabled tmp.mount  # noqa: command-instead-of-module
      changed_when: false
      failed_when: prelim_tmp_mnt_type.rc not in [ 0, 1 ]
      check_mode: false
      register: prelim_tmp_mnt_type

    - name: PRELIM | Capture tmp mount type | Set to ubtu20cis_expected_tmp_mnt variable
      when: "'generated' in prelim_tmp_mnt_type.stdout"
      ansible.builtin.set_fact:
        prelim_tmp_mnt_type: "{{ ubtu20cis_expected_tmp_mnt }}"

    - name: PRELIM | Capture tmp mount type | Set systemd service
      when:
        - prelim_tmp_mnt_type.stdout is defined
        - "'generated' not in prelim_tmp_mnt_type.stdout"
      ansible.builtin.set_fact:
        prelim_tmp_mnt_type: tmp_systemd

- name: "PRELIM | register if snap being used"
  tags:
    - rule_1.1.1.7
    - always
  ansible.builtin.shell: df -h | grep -wc "/snap"
  changed_when: false
  failed_when: prelim_snap_pkg_mgr.rc not in [ 0, 1 ]
  check_mode: false
  register: prelim_snap_pkg_mgr

- name: "PRELIM | Run apt update"
  when: ubtu20cis_rule_1_2_1_1 or ubtu20cis_rule_1_2_2_1
  tags:
    - rule_1.2.1.1
    - rule_1.2.2.1
    - always
  ansible.builtin.package:
    update_cache: true

- name: "PRELIM | Check for autofs service"
  when: ubtu20cis_rule_2_1_1
  tags:
    - rule_2.1.1
    - section2
    - always
  ansible.builtin.shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"  # noqa: command-instead-of-module command-instead-of-shell
  changed_when: false
  check_mode: false
  register: prelim_autofs_service_status

- name: "PRELIM | Check for avahi-daemon service"
  when: ubtu20cis_rule_2_1_2
  tags:
    - rule_2.1.2
    - always
  ansible.builtin.shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"  # noqa: command-instead-of-module command-instead-of-shell
  changed_when: false
  check_mode: false
  register: prelim_avahi_service_status

- name: "PRELIM | Find wireless network devices"
  when: ubtu20cis_rule_3_1_2
  tags:
    - rule_3.1.2
    - always
  ansible.builtin.shell: find /sys/class/net/*/wireless | awk -F'/' awk '{print $5}'
  changed_when: false
  failed_when: prelim_wireless_interfaces.rc not in [ 0, 2 ]
  check_mode: false
  register: prelim_wireless_interfaces

- name: "PRELIM | PATCH | Ensure auditd is installed"
  when:
    - ubtu20cis_rule_6_3_1_1
    - "'auditd' not in ansible_facts.packages or 'auditd-plugins' not in ansible_facts.packages"
    - ubtu20cis_rule_6_3_4_5 or ubtu20cis_rule_6_3_4_6 or ubtu20cis_rule_6_3_4_7
  tags:
    - level2-server
    - level2-workstation
    - patch
    - auditd
    - always
  block:
    - name: "PRELIM | PATCH | Ensure auditd is installed"
      ansible.builtin.package:
        name: ['auditd', 'audispd-plugins']
        state: present

    - name: "PRELIM | 6.3.4.5 | Audit conf and rules files | list files"
      ansible.builtin.find:
        path: /etc/audit/
        file_type: file
        recurse: true
        patterns: '*.conf,*.rules'
      register: prelim_auditd_conf_files

- name: "PRELIM | Discover Interactive UID MIN and MIN from logins.def"
  when: not discover_int_uid
  tags: always
  block:
    - name: "PRELIM | Capture UID_MIN information from logins.def"
      ansible.builtin.shell: grep -w "^UID_MIN" /etc/login.defs | awk '{print $NF}'
      changed_when: false
      check_mode: false
      register: prelim_uid_min_id

    - name: "PRELIM | Capture UID_MAX information from logins.def"
      ansible.builtin.shell: grep -w "^UID_MAX" /etc/login.defs | awk '{print $NF}'
      changed_when: false
      check_mode: false
      register: prelim_uid_max_id

    - name: "PRELIM | Capture GID_MIN information from logins.def"
      ansible.builtin.shell: grep -w "^GID_MIN" /etc/login.defs | awk '{print $NF}'
      changed_when: false
      check_mode: false
      register: prelim_gid_min_id

    - name: "PRELIM | set_facts for interactive uid/gid"
      ansible.builtin.set_fact:
        min_int_uid: "{{ prelim_uid_min_id.stdout }}"
        max_int_uid: "{{ prelim_uid_max_id.stdout }}"
        min_int_gid: "{{ prelim_gid_min_id.stdout }}"

- name: "PRELIM | Interactive User accounts"
  tags: always
  ansible.builtin.shell: 'cat /etc/passwd | cut -d: -f5,6,7 | grep -Ev ":(/usr|)/(s|)bin/nologin|/root|:/bin:" | cut -d: -f2'
  changed_when: false
  check_mode: false
  register: prelim_interactive_users_home

- name: "PRELIM | Install Network-Manager"
  when:
    - prelim_wireless_interfaces.stdout is defined
    - prelim_wireless_interfaces.stdout | length > 0
    - ubtu20cis_install_network_manager
    - ubtu20cis_rule_3_1_2
    - not ubtu20cis_system_is_container
  tags:
    - rule_3.1.2
    - always
  ansible.builtin.package:
    name: network-manager
    state: present

- name: "PRELIM | AUDIT | Capture pam config related files"
  tags: always
  ansible.builtin.find:
    paths:
      - '/usr/share/pam-configs/'
      - '/etc/pam.d/'
  register: prelim_pam_conf_files

- name: "PRELIM | PATCH | Ensure conf.d directory exists required for 5.3.3.2.x"
  when:
    - ubtu20cis_rule_5_3_3_2_1 or
      ubtu20cis_rule_5_3_3_2_2 or
      ubtu20cis_rule_5_3_3_2_3 or
      ubtu20cis_rule_5_3_3_2_4 or
      ubtu20cis_rule_5_3_3_2_5 or
      ubtu20cis_rule_5_3_3_2_6
  tags: always
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: root
    group: root
    mode: 'g-w,o-rwx'
    modification_time: preserve
    access_time: preserve
  changed_when: prelim_pwquality_dummy.changed
  register: prelim_pwquality_dummy
  loop:
    - { path: '/etc/security/pwquality.conf.d', state: 'directory' }
    - { path: '/etc/security/pwquality.conf.d/cis_dummy.conf', state: 'touch' }

- name: "PRELIM | AUDIT | Capture pam security related files"
  tags: always
  ansible.builtin.find:
    paths:
      - /etc/security/pwquality.conf.d/
    patterns: '*.conf'
  register: prelim_pam_pwquality_confs

- name: "PRELIM | 5.2.4 | Find all sudoers files."
  when: ubtu20cis_rule_5_2_4 or ubtu20cis_rule_5_2_5
  tags: always
  ansible.builtin.shell: "find /etc/sudoers /etc/sudoers.d/ -type f ! -name '*~' ! -name '*.*'"
  changed_when: false
  failed_when: false
  check_mode: false
  register: prelim_sudoers_files

- name: "PRELIM | Install ACL"
  when: ubtu20cis_rule_7_2_6
  tags:
    - rule_7.2.6
    - always
  ansible.builtin.package:
    name: acl
    state: present

- name: "PRELIM | List users accounts"
  when: ubtu20cis_rule_7_2_8 or ubtu20cis_rule_7_2_9 or ubtu20cis_rule_5_4_2_1 or ubtu20cis_rule_7_2_10
  tags: always
  ansible.builtin.shell: "awk -F: '{print $1}' /etc/passwd"
  changed_when: false
  check_mode: false
  register: prelim_users

- name: "PRELIM | Discover UID 0 accounts other than root"
  when: ubtu20cis_rule_5_4_2_1
  tags: always
  ansible.builtin.shell: "awk -F: '($3 == 0 && $1 != \"root\") {print $1}' /etc/passwd"
  changed_when: false
  failed_when: prelim_uid_zero_accounts_except_root.rc not in [ 0, 1 ]
  check_mode: false
  register: prelim_uid_zero_accounts_except_root

- name: "PRELIM | Discover interactive user accounts"
  when: ubtu20cis_rule_5_4_2_8
  tags: always
  ansible.builtin.shell: >-
    awk -F: '($7 !~ /nologin/ && $7 !~ /false/ && $7 !~ /sync/ && $7 !~ /halt/ && $7 !~ /shutdown/) {print $1}' /etc/passwd
  changed_when: false
  check_mode: false
  register: prelim_interactive_usernames
