---
- name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console"
  block:
      - name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console | Get list of all terminals"
        command: cat /etc/securetty
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_5_6_terminal_list

      - name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console | Message out list"
        debug:
            msg:
                - "WARNING!!!! Below is the list of consoles with root login access"
                - "Please review for any consoles that are not in a physically secure location"
                - "{{ ubtu20cis_5_6_terminal_list.stdout_lines }}"
  when:
      - ubtu20cis_rule_5_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_5.6
      - user
