---
- name: "5.2.1.1 | PATCH | Ensure auditd is installed"
  ansible.builtin.package:
      name: ['auditd', 'audispd-plugins']
      state: present
  when:
      - ubtu20cis_rule_5_2_1_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_5.2.1.1
      - auditd

- name: "5.2.1.2 | PATCH | Ensure auditd service is enabled and active"
  ansible.builtin.service:
      name: auditd
      state: started
      enabled: true
  when:
      - ubtu20cis_rule_5_2_1_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_5.2.1.2
      - auditd

- name: "5.2.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  block:
      - name: "5.2.1.3 | AUDIT | Ensure auditing for processes that start prior to auditd is enabled | Get GRUB_CMDLINE_LINUX"
        ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_5_2_1_3_cmdline_settings

      - name: "5.2.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Add setting if doesn't exist"
        ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu20cis_5_2_1_3_cmdline_settings.stdout }} audit=1"'
        when: "'audit=' not in ubtu20cis_5_2_1_3_cmdline_settings.stdout"
        notify: Grub update

      - name: "5.2.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Update setting if exists"
        ansible.builtin.replace:
            dest: /etc/default/grub
            regexp: 'audit=([0-9]+)'
            replace: 'audit=1'
            after: '^GRUB_CMDLINE_LINUX="'
            before: '"'
        notify: Grub update
        when: "'audit=' in ubtu20cis_5_2_1_3_cmdline_settings.stdout"
  when:
      - ubtu20cis_rule_5_2_1_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_5_2_1_3
      - auditd

- name: "5.2.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  block:
      - name: "5.2.1.4 | PATCH | Ensure audit_backlog_limit is sufficient | Get current GRUB_CMDLINE_LINUX"
        ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_5_2_1_4_cmdline_settings

      - name: "5.2.1.4 | PATCH | Ensure audit_backlog_limit is sufficient | Add setting if doesn't exist"
        ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu20cis_5_2_1_4_cmdline_settings.stdout }} audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }}"'
        notify: Grub update
        when: "'audit_backlog_limit=' not in ubtu20cis_5_2_1_4_cmdline_settings.stdout"

      - name: "5.2.1.4 | PATCH | Ensure audit_backlog_limit is sufficient | Update setting if exists"
        ansible.builtin.replace:
            dest: /etc/default/grub
            regexp: 'audit_backlog_limit=([0-9]+)'
            replace: 'audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }}'
            after: '^GRUB_CMDLINE_LINUX="'
            before: '"'
        notify: Grub update
  when:
      - ubtu20cis_rule_5_2_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_5.2.1.4
      - auditd
