---
- name: "5.6 | AUDIT | Ensure root login is restricted to system console"
  block:
      - name: "5.6 | AUDIT | Ensure root login is restricted to system console | Get list of all terminals"
        ansible.builtin.shell: cat /etc/securetty
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_5_6_terminal_list

      - name: "5.6 | AUDIT | Ensure root login is restricted to system console | Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '5.6'
  when:
      - ubtu20cis_rule_5_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_5.6
      - user
