---

- name: "5.1.1.2 | Ensure journald service is enabled"
  block:
      - name: "5.1.1.2 | Ensure journald service is enabled | capture status"
        ansible.builtin.shell: systemctl is-enabled systemd-journald.service
        register: ubtu20cis_5_1_1_2_journald_enabled
        changed_when: false
        failed_when: ubtu20cis_5_1_1_2_journald_enabled.rc not in [ 0, 1, 2 ]

      - name: "5.1.1.2 | Ensure journald service is enabled | warn count if not as expected"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        when: "'static' not in ubtu20cis_5_1_1_2_journald_enabled.stdout"
  vars:
      warn_control_id: '5.1.1.2'
  when:
      - ubtu20cis_rule_5_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.1.1.2
      - journald

- name: "5.1.1.3 | PATCH | Ensure journald is configured to compress large log files"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Compress|^#Compress'
      line: 'Compress=yes'
      insertafter: '\[Journal\]'
  when:
      - ubtu20cis_rule_5_1_1_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.1.1.3
      - journald

- name: "5.1.1.4 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Storage|^#Storage'
      line: 'Storage=persistent'
      insertafter: '\[Journal\]'
  when:
      - ubtu20cis_rule_5_1_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.1.1.4
      - journald

- name: "5.1.1.5 | PATCH | Ensure journald is not configured to send logs to rsyslog"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^ForwardToSyslog|^#ForwardToSyslog'
      line: 'ForwardToSyslog=no'
      insertafter: '\[Journal\]'
  when:
      - ubtu20cis_rule_5_1_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.1.1.5
      - journald

- name: "5.1.1.6 | PATCH | Ensure journald log rotation is configured per site policy"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  loop:
      - { regexp: 'SystemMaxUse=', line: "SystemMaxUse={{ ubtu20cis_journald_log_rotate.systemmaxuse }}" }
      - { regexp: 'SystemKeepFree=', line: "SystemKeepFree={{ ubtu20cis_journald_log_rotate.systemkeepfree }}" }
      - { regexp: 'RunTimeMaxUse=', line: "RunTimeMaxUse={{ ubtu20cis_journald_log_rotate.runtimemaxuse }}" }
      - { regexp: 'RuntimeKeepFree=', line: "RuntimeKeepFree={{ ubtu20cis_journald_log_rotate.runtimekeepfree }}" }
      - { regexp: 'MaxFileSec=', line: "MaxFileSec={{ ubtu20cis_journald_log_rotate.maxfilesec }}" }
  when:
      - ubtu20cis_rule_5_1_1_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.1.1.6
      - journald

- name: "5.1.1.7 | PATCH | Ensure journald default file permissions configured"
  block:
      - name: "5.1.1.7 | AUDIT | Ensure journald default file permissions configured | check for override file"
        ansible.builtin.stat:
            path: /etc/tmpfiles.d/systemd.conf
        register: ubtu20cis_5_1_1_7_tmpfile

      - name: "5.1.1.7 | AUDIT | Ensure journald default file permissions configured | update settings if override exists"
        ansible.builtin.lineinfile:
            path: /etc/tmpfiles.d/systemd.conf
            regexp: "{{ item.line }}"
            line: "{{ item.line }}"
            backrefs: true
        when: ubtu20cis_5_1_1_7_tmpfile.stat.exists
        loop:
            - { regexp: '.*system.journal.*(:r(w|-)(x|-))(,|$)', line: 'a+ /var/log/journal/%m/system.journal - - - - group:adm:r--'}
            - { regexp: '.*\/var\/log\/journal\/\%m\s.*(:r(w|-)(x|-))(,|$)', line: 'a+ /var/log/journal/%m - - - - d:group:adm:r-x,group:adm:r-x'}
            - { regexp: '.*\/var\/log\/journal\s.*(:r(w|-)(x|-))(,|$)', line: 'a+ /var/log/journal    - - - - d:group::r-x,d:group:adm:r-x,group::r-x,group:adm:r-x'}
