---

- name: |
      "5.2.4.1 | PATCH | Ensure audit log files are mode 0640 or less permissive"
      "5.2.4.2 | PATCH | Ensure only authorized users own audit log files"
      "5.2.4.3 | PATCH | Ensure only authorized groups are assigned ownership of audit log files"

  block:
      - name: "5.2.4.1 | AUDIT | Ensure audit log files are mode 0640 or less permissive | discover file"
        ansible.builtin.shell: grep ^log_file /etc/audit/auditd.conf | awk '{ print $NF }'
        changed_when: false
        register: audit_discovered_logfile

      - name: "5.2.4.1 | AUDIT | Ensure audit log files are mode 0640 or less permissive | stat file"
        ansible.builtin.stat:
            path: "{{ audit_discovered_logfile.stdout }}"
        changed_when: false
        register: auditd_logfile

      - name: |
            "5.2.4.1 | PATCH | Ensure audit log files are mode 0640 or less permissive"
            "5.2.4.2 | PATCH | Ensure only authorized users own audit log files"
            "5.2.4.3 | PATCH | Ensure only authorized groups are assigned ownership of audit log files"
        ansible.builtin.file:
            path: "{{ audit_discovered_logfile.stdout }}"
            mode: "{% if auditd_logfile.stat.mode > '0640' %}0640{% endif %}"
            owner: root
            group: root
  when:
      - ubtu20cis_rule_5_2_4_1 or
        ubtu20cis_rule_5_2_4_2 or
        ubtu20cis_rule_5_2_4_3
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.1
      - rule_5.2.4.2
      - rule_5.2.4.3

- name: "5.2.4.4 | PATCH | Ensure the audit log directory is 0750 or more restrictive"
  block:
      - name: "5.2.4.4 | AUDIT | Ensure the audit log directory is 0750 or more restrictive | get current permissions"
        ansible.builtin.stat:
            path: "{{ audit_discovered_logfile.stdout | dirname }}"
        register: auditlog_dir

      - name: "5.2.4.4 | PATCH | Ensure the audit log directory is 0750 or more restrictive | set"
        ansible.builtin.file:
            path: "{{ audit_discovered_logfile.stdout | dirname }}"
            state: directory
            mode: 0750
        when: not auditlog_dir.stat.mode is match('07(0|5)0')
  when:
      - ubtu20cis_rule_5_2_4_4
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.4

- name: "5.2.4.5 | PATCH | Ensure audit configuration files are 640 or more restrictive"
  ansible.builtin.file:
      path: "{{ item.path }}"
      mode: '0640'
  loop: "{{ auditd_conf_files.files }}"
  loop_control:
      label: "{{ item.path }}"
  when:
      - item.mode > '0640'
      - ubtu20cis_rule_5_2_4_5
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.5

- name: "5.2.4.6 | PATCH | Ensure audit configuration files are owned by root"
  ansible.builtin.file:
      path: "{{ item.path }}"
      owner: root
  loop: "{{ auditd_conf_files.files }}"
  loop_control:
      label: "{{ item.path }}"
  when:
      - ubtu20cis_rule_5_2_4_6
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.6

- name: "5.2.4.7 | PATCH | Ensure audit configuration files belong to group root"
  ansible.builtin.file:
      path: "{{ item.path }}"
      group: root
  loop: "{{ auditd_conf_files.files }}"
  loop_control:
      label: "{{ item.path }}"
  when:
      - ubtu20cis_rule_5_2_4_7
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.7

- name: "5.2.4.8 | PATCH | Ensure audit tools are 755 or more restrictive"
  block:
      - name: "5.2.4.8 | AUDIT | Get audit binary file stat | get current mode"
        ansible.builtin.stat:
            path: "{{ item }}"
        register: "audit_bins"
        loop:
            - /sbin/auditctl
            - /sbin/aureport
            - /sbin/ausearch
            - /sbin/autrace
            - /sbin/auditd
            - /sbin/augenrules

      - name: "5.2.4.8 | PATCH | Ensure audit tools are 755 or more restrictive | set if required"
        ansible.builtin.file:
            path: "{{ item.item }}"
            mode: 0750

        loop: "{{ audit_bins.results }}"
        loop_control:
            label: "{{ item.item }}"
        when: not item.stat.mode is match('07(0|5)0')
  when:
      - ubtu20cis_rule_5_2_4_8
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.8

- name: "5.2.4.9 | PATCH | Ensure audit tools are owned by root"
  ansible.builtin.file:
      path: "{{ item }}"
      owner: root
      group: root
  loop:
      - /sbin/auditctl
      - /sbin/aureport
      - /sbin/ausearch
      - /sbin/autrace
      - /sbin/auditd
      - /sbin/augenrules
  when:
      - ubtu20cis_rule_5_2_4_9
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.9

- name: "5.2.4.10 | PATCH | Ensure audit tools belong to group root"
  ansible.builtin.file:
      path: "{{ item }}"
      group: root
  loop:
      - /sbin/auditctl
      - /sbin/aureport
      - /sbin/ausearch
      - /sbin/autrace
      - /sbin/auditd
      - /sbin/augenrules
  when:
      - ubtu20cis_rule_5_2_4_10
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.10

- name: "5.2.4.11 | PATCH | Ensure cryptographic mechanisms are used to protect the integrity of audit tools"
  ansible.builtin.lineinfile:
      path: /etc/aide/aide.conf
      regexp: "{{ item }}"
      line: "{{ item }}"
  loop:
      - '# Audit tools'
      - /sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
      - /sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
      - /sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
      - /sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
      - /sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
      - /sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
  when:
      - ubtu20cis_rule_5_2_4_11
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_5.2.4.11
