---

- name: Remount tmp
  ansible.posix.mount:
    name: /tmp
    state: remounted

- name: Remount dev_shm
  ansible.posix.mount:
    name: /dev/shm
    state: remounted

- name: Remount var
  ansible.posix.mount:
    name: /var
    state: remounted

- name: Remount var_tmp
  ansible.posix.mount:
    name: /var/tmp
    state: remounted

- name: Remount var_log
  ansible.posix.mount:
    name: /var/log
    state: remounted

- name: Remount var_log_audit
  ansible.posix.mount:
    name: /var/log/audit
    state: remounted

- name: Remount home
  ansible.posix.mount:
    name: /home
    state: remounted

- name: Grub update
  ansible.builtin.command: update-grub
  notify: Change requires reboot
  changed_when: true
  failed_when: false

- name: Update dconf
  ansible.builtin.command: dconf update
  changed_when: true

- name: Restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: Restart exim4
  ansible.builtin.systemd:
    name: exim4
    state: restarted

- name: Restart timeservice
  ansible.builtin.systemd:
    name: "{{ ubtu20cis_time_sync_tool }}"
    state: restarted
# ---------------
# ---------------
# This is not a control however using the iptables module only writes to memory
# if a reboot occurs that means changes can revert. This task will make the
# above iptables settings permanent
#
# This is also idempotent as a handler
# ---------------
# ---------------

- name: Persistent ip4tables
  ansible.builtin.shell: bash -c "iptables-save > /etc/iptables/rules.v4"
  changed_when: discovered_iptables_save.rc == 0
  failed_when: discovered_iptables_save.rc > 0
  register: discovered_iptables_save

- name: Sysctl flush ipv4 route table
  when: ansible_virtualization_type != "docker"
  ansible.posix.sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: true

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Sysctl flush ipv6 route table
  when: ansible_virtualization_type != "docker"
  ansible.posix.sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: true

- name: Restart auditd
  when: not ubtu20cis_skip_for_travis
  tags: skip_ansible_lint
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Restart syslog service
  ansible.builtin.systemd:
    name: "{{ ubtu20cis_syslog_service }}"
    state: restarted

- name: Restart journal-upload
  ansible.builtin.systemd:
    name: systemd-journal-upload
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Pam auth update pwunix
  ansible.builtin.command: pam-auth-update --enable {{ ubtu20cis_pam_pwunix_file }}
  changed_when: true

- name: Pam auth update pwfaillock
  ansible.builtin.command: pam-auth-update --enable {{ ubtu20cis_pam_faillock_file }}
  changed_when: true

- name: Pam auth update pwfaillock notify
  ansible.builtin.command: pam-auth-update --enable {{ ubtu20cis_pam_faillock_notify_file }}
  changed_when: true

- name: Pam auth update pwquality
  ansible.builtin.command: pam-auth-update --enable {{ ubtu20cis_pam_pwquality_file }}
  changed_when: true

- name: Pam auth update pwhistory
  ansible.builtin.command: pam-auth-update --enable {{ ubtu20cis_pam_pwhistory_file }}
  changed_when: true

- name: Change requires reboot
  ansible.builtin.set_fact:
    change_requires_reboot: true
