---

# ---------------
# ---------------
# NFTables is unsupported with this role. However we have the actions commented out as a guide
# ---------------
# ---------------

- name: "3.4.2.1 | AUDIT | Ensure nftables is installed"
  ansible.builtin.package:
      name: nftables
      state: present
  when:
      - ubtu20cis_rule_3_4_2_1
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.1
      - nftables

- name: "3.4.2.2 | AUDIT | Ensure ufw is uninstalled or disabled with nftables"
  ansible.builtin.package:
      name: ufw
      state: absent
  when:
      - ubtu20cis_rule_3_4_2_2
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.2
      - nftables

- name: "3.4.2.3 | AUDIT | Ensure iptables are flushed with nftables"
  block:
      - name: "3.4.2.3 | AUDIT | Ensure iptables are flushed with nftables"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.3 | AUDIT | Ensure iptables are flushed with nftables | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.3'
  when:
      - ubtu20cis_rule_3_4_2_3
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.4.2.3
      - nftables

- name: "3.4.2.4 | AUDIT | Ensure a nftables table exists"
  block:
      - name: "3.4.2.4 | AUDIT | Ensure a nftables table exists"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.4 | AUDIT | Ensure a nftables table exists | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.4'
  when:
      - ubtu20cis_rule_3_4_2_4
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.4.2.4
      - nftables

- name: "3.4.2.5 | AUDIT | Ensure nftables base chains exist"
  block:
      - name: "3.4.2.5 | AUDIT | Ensure nftables base chains exist"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.5 | AUDIT | Ensure nftables base chains exist | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.5'
  when:
      - ubtu20cis_rule_3_4_2_5
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.5
      - nftables

- name: "3.4.2.6 | AUDIT | Ensure nftables loopback traffic is configured"
  block:
      - name: "3.4.2.6 | AUDIT | Ensure nftables loopback traffic is configured"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.6 | AUDIT | Ensure nftables loopback traffic is configured | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.6'
  when:
      - ubtu20cis_rule_3_4_2_6
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.6
      - nftables

- name: "3.4.2.7 | AUDIT | Ensure nftables outbound and established connections are configured"
  block:
      - name: "3.4.2.7 | AUDIT | Ensure nftables outbound and established connections are configured"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.7 | AUDIT | Ensure nftables outbound and established connections are configured | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.7'
  when:
      - ubtu20cis_rule_3_4_2_7
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.4.2.7
      - nftables

- name: "3.4.2.8 | AUDIT | Ensure nftables default deny firewall policy"
  block:
      - name: "3.4.2.8 | AUDIT | Ensure nftables default deny firewall policy"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.8 | AUDIT | Ensure nftables default deny firewall policy | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.8'
  when:
      - ubtu20cis_rule_3_4_2_8
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.8
      - nftables

- name: "3.4.2.9 | AUDIT | Ensure nftables service is enabled"
  block:
      - name: "3.4.2.9 | AUDIT | Ensure nftables service is enabled"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.9 | AUDIT | Ensure nftables service is enabled | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.9'
  when:
      - ubtu20cis_rule_3_4_2_9
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.9
      - nftables

- name: "3.4.2.10 | AUDIT | Ensure nftables rules are permanent"
  block:
      - name: "3.4.2.10 | AUDIT | Ensure nftables rules are permanent"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.4.2.10 | AUDIT | Ensure nftables rules are permanent | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.10'
  when:
      - ubtu20cis_rule_3_4_2_10
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.4.2.10
      - nftables
