---
- name: "3.4.1.1 | PATCH | Ensure ufw is installed"
  ansible.builtin.package:
      name: ufw
      state: present
  when:
      - ubtu20cis_rule_3_4_1_1
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.4.1.1
      - apt
      - ufw

- name: "3.4.1.2 | PATCH | Ensure iptables-persistent is not installed with ufw"
  ansible.builtin.package:
      name: iptables-persistent
      state: absent
  when:
      - ubtu20cis_rule_3_4_1_2
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.4.1.2
      - ufw

# Adding the allow OpenSSH rule while enabling ufw to allow ansible to run after enabling
- name: "3.4.1.3 | PATCH | Ensure ufw service is enabled"
  community.general.ufw:
      rule: allow
      name: OpenSSH
      state: enabled
  when:
      - ubtu20cis_rule_3_4_1_3
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.4.1.3
      - ufw

- name: "3.4.1.4 | PATCH | Ensure loopback traffic is configured"
  block:
      - name: "3.4.1.4 | PATCH | Ensure loopback traffic is configured | Set allow in ufw rules"
        community.general.ufw:
            rule: allow
            direction: in
            interface: lo
        notify: reload ufw

      - name: "3.4.1.4 | PATCH | Ensure loopback traffic is configured | Set allow out ufw rules"
        community.general.ufw:
            rule: allow
            direction: out
            interface: lo
        notify: reload ufw

      - name: "3.4.1.4 | PATCH | Ensure loopback traffic is configured | Set deny ufw rules IPv4"
        community.general.ufw:
            rule: deny
            direction: in
            from_ip: 127.0.0.0/8
        notify: reload ufw

      - name: "3.4.1.4 | PATCH | Ensure loopback traffic is configured | Set deny ufw rules IPv6"
        community.general.ufw:
            rule: deny
            direction: in
            from_ip: "::1"
        notify: reload ufw
        when: ubtu20cis_ipv6_required
  when:
      - ubtu20cis_rule_3_4_1_4
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.4.1.4
      - ufw

- name: "3.4.1.5 | PATCH | Ensure ufw outbound connections are configured"
  block:
      - name: "3.4.1.5 | PATCH | Ensure ufw outbound connections are configured | Custom ports"
        community.general.ufw:
            rule: allow
            direction: out
            to_port: '{{ item }}'
        with_items:
            - "{{ ubtu20cis_ufw_allow_out_ports }}"
        notify: reload ufw
        when: ubtu20cis_ufw_allow_out_ports != "all"

      - name: "3.4.1.5 | PATCH | Ensure ufw outbound connections are configured | Allow all"
        community.general.ufw:
            rule: allow
            direction: out
        notify: reload ufw
        when: "'all' in ubtu20cis_ufw_allow_out_ports"
  when:
      - ubtu20cis_rule_3_4_1_5
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_3.4.1.5
      - ufw

- name: "3.4.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports"
  block:
      - name: "3.4.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Get list of open ports"
        ansible.builtin.shell: ss -4tuln
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_3_4_1_6_open_listen_ports

      - name: "3.4.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Get list of firewall rules"
        ansible.builtin.shell: ufw status
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_3_4_1_6_firewall_rules

      - name: "3.4.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Message out settings"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the listening ports and firewall rules"
                - "Please create firewall rule for any open ports if not already done"
                - "*****---Open Listen Ports---*****"
                - "{{ ubtu20cis_3_4_1_6_open_listen_ports.stdout_lines }}"
                - "*****---Firewall Rules---*****"
                - "{{ ubtu20cis_3_4_1_6_firewall_rules.stdout_lines }}"

      - name: "3.4.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.4.1.6'

  when:
      - ubtu20cis_rule_3_4_1_6
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.4.1.6
      - ufw

- name: "OPTIONAL | UFW incoming ports"
  community.general.ufw:
      rule: allow
      direction: in
      from_ip: '{{ item.from }}'
      to_port: '{{ item.port }}'
      proto: '{{ item.proto }}'
  loop: "{{ ubtu20cis_ufw_allow_in }}"
  loop_control:
      label: "{{ item.port }}"
  notify: reload ufw
  when: ufw_add_incoming
  tags:
      - ufw
      - ufw_in_ports

- name: "3.4.1.7 | PATCH | Ensure ufw default deny firewall policy"
  community.general.ufw:
      default: deny
      direction: "{{ item }}"
  notify: reload ufw
  with_items:
      - incoming
      - outgoing
      - routed
  when:
      - ubtu20cis_rule_3_4_1_7
      - ubtu20cis_firewall_package == "ufw"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.4.1.7
      - ufw
