---
- name: "SECTION | 3.1 | Disable unused network protocols and devices"
  ansible.builtin.import_tasks:
      file: cis_3.1.x.yml

- name: "SECTION | 3.2 | Network Parameters Host Only"
  ansible.builtin.import_tasks:
      file: cis_3.2.x.yml

- name: "SECTION | 3.3 | Network Parameters Host and Router"
  ansible.builtin.import_tasks:
      file: cis_3.3.x.yml

- name: "SECTION | 3.4.1 | Firewall Configuration UFW"
  ansible.builtin.import_tasks:
      file: cis_3.4.1.x.yml
  when:
      - ubtu20cis_firewall_package == "ufw"

- name: "SECTION | 3.4.2 | Firewall Configuration nftables"
  ansible.builtin.import_tasks:
      file: cis_3.4.2.x.yml
  when:
      - ubtu20cis_firewall_package == "nftables"

- name: "SECTION | 3.4.3 | Firewall Configuration iptables"
  ansible.builtin.import_tasks:
      file: cis_3.4.3.x.yml
  when:
      - ubtu20cis_firewall_package == "iptables"
