---

- name: "6.3.1.1 | PATCH | Ensure auditd is installed"
  when: ubtu20cis_rule_6_3_1_1
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.1.1
    - auditd
  ansible.builtin.package:
    name: ['auditd', 'audispd-plugins']
    state: present

- name: "6.3.1.2 | PATCH | Ensure auditd service is enabled and active"
  when: ubtu20cis_rule_6_3_1_2
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.1.2
    - auditd
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

- name: "6.3.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  when: ubtu20cis_rule_6_3_1_3
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.1.3
    - auditd
  block:
    - name: "6.3.1.3 | AUDIT | Ensure auditing for processes that start prior to auditd is enabled | Get GRUB_CMDLINE_LINUX"
      ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_auditd_cmdline_settings

    - name: "6.3.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Add setting if doesn't exist"
      when: "'audit=' not in discovered_auditd_cmdline_settings.stdout"
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="{{ discovered_auditd_cmdline_settings.stdout }} audit=1"'
      notify: grub update

    - name: "6.3.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Update setting if exists"
      when: "'audit=' in discovered_auditd_cmdline_settings.stdout"
      ansible.builtin.replace:
        dest: /etc/default/grub
        regexp: 'audit=([0-9]+)'
        replace: 'audit=1'
        after: '^GRUB_CMDLINE_LINUX="'
        before: '"'
      notify: grub update

- name: "6.3.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  when: ubtu20cis_rule_6_3_1_4
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.1.4
    - auditd
  block:
    - name: "6.3.1.4 | PATCH | Ensure audit_backlog_limit is sufficient | Get current GRUB_CMDLINE_LINUX"
      ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_auditd_backlog_cmdline

    - name: "6.3.1.4 | PATCH | Ensure audit_backlog_limit is sufficient | Add setting if doesn't exist"
      when: "'audit_backlog_limit=' not in discovered_auditd_backlog_cmdline.stdout"
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="{{ discovered_auditd_backlog_cmdline.stdout }} audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }}"'
      notify: grub update

    - name: "6.3.1.4 | PATCH | Ensure audit_backlog_limit is sufficient | Update setting if exists"
      ansible.builtin.replace:
        dest: /etc/default/grub
        regexp: 'audit_backlog_limit=([0-9]+)'
        replace: 'audit_backlog_limit={{ ubtu20cis_audit_back_log_limit }}'
        after: '^GRUB_CMDLINE_LINUX="'
        before: '"'
      notify: grub update

- name: "6.3.2.1 | PATCH | Ensure audit log storage size is configured"
  when: ubtu20cis_rule_6_3_2_1
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.2.1
    - auditd
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^max_log_file( |=)"
    line: "max_log_file = {{ ubtu20cis_max_log_file_size }}"
    state: present
  notify: restart auditd

- name: "6.3.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  when: ubtu20cis_rule_6_3_2_2
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.2.2
    - auditd
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file_action'
    line: "max_log_file_action = {{ ubtu20cis_auditd['max_log_file_action'] }}"
  notify: restart auditd

- name: "6.3.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  when: ubtu20cis_rule_6_3_2_3
  tags:
    - level2-server
    - level2-workstation
    - automated
    - patch
    - rule_6.3.2.3
    - auditd
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: '^space_left_action', line: 'space_left_action = email'}
    - {regexp: '^action_mail_acct', line: 'action_mail_acct = root'}
    - {regexp: '^admin_space_left_action', line: "admin_space_left_action = {{ ubtu20cis_auditd['admin_space_left_action'] }}"}
  notify: restart auditd

- name: "6.3.2.4 | PATCH | Ensure audit log file space warning is configured"
  when: ubtu20cis_rule_6_3_2_4
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_6.3.2.4
  block:
    - name: "6.3.2.4 | AUDIT | Ensure audit log file space warning is configured | check status"
      ansible.builtin.debug:
        msg: "This control requires manual remediation"

    - name: "6.3.2.4 | AUDIT | Ensure audit log file space warning is configured | Warn Count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '6.3.2.4'
