---

- name: "SECTION | 6.1 | AIDE File Integrity Checking"
  ansible.builtin.import_tasks:
    file: cis_6.1.x.yml

- name: "SECTION | 6.2 | Configure journald"
  when: ubtu20cis_syslog_service == 'journald'
  ansible.builtin.import_tasks:
    file: cis_6.2.x.yml

- name: "SECTION | 6.2.3 | Configure rsyslog"
  when: ubtu20cis_syslog_service == 'rsyslog'
  ansible.builtin.import_tasks:
    file: cis_6.2.3.x.yml

- name: "SECTION | 6.3 | Configure auditd"
  ansible.builtin.import_tasks:
    file: cis_6.3.x.yml

- name: "SECTION | 6.3.3 | Configure auditd rules"
  ansible.builtin.import_tasks:
    file: cis_6.3.3.x.yml

- name: "SECTION | 6.3.4 | Configure auditd file access"
  ansible.builtin.import_tasks:
    file: cis_6.3.4.x.yml
