---
- name: "2.3 | AUDIT | Ensure nonessential services are removed or masked"
  block:
      - name: "2.3 | AUDIT | Ensure nonessential services are removed or masked | Check for services"
        ansible.builtin.shell: lsof -i -P -n | grep -v "(ESTABLISHED)"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_2_3_services

      - name: "2.3 | AUDIT | Ensure nonessential services are removed or masked | Message out running services"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the running services. Please review and remove as well as mask un-needed services"
                - "{{ ubtu20cis_2_3_services.stdout_lines }}"

      - name: "2.3 | AUDIT | Ensure nonessential services are removed or masked | Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '2.3'
  when:
      - ubtu20cis_rule_2_3
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_2.3
      - services
