---

- name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured"
  when: ubtu20cis_rule_1_2_1_1
  tags:
    - level1-server
    - level1-workstation
    - manual
    - audit
    - rule_1.2.1.1
    - gpg
    - keys
  block:
    - name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured | Get apt gpg keys"
      ansible.builtin.command: apt-key list
      changed_when: false
      failed_when: false
      check_mode: false
      register: ubtu20cis_1_2_1_1_apt_gpgkeys

    - name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured | Message out apt gpg keys"
      ansible.builtin.debug:
        msg:
          - "Warning!!  Below are the apt gpg keys configured"
          - "Please review to make sure they are configured"
          - "in accordance with site policy"
          - "{{ ubtu20cis_1_2_1_1_apt_gpgkeys.stdout_lines }}"

    - name: "1.2.1.1 | AUDIT | Ensure GPG keys are configured | Warn Count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '1.2.1.1'

- name: "1.2.1.2 | AUDIT | Ensure package manager repositories are configured"
  when: ubtu20cis_rule_1_2_1_2
  tags:
    - level1-server
    - level1-workstation
    - manual
    - audit
    - rule_1.2.1.2
    - apt
  block:
    - name: "1.2.1.2 | AUDIT | Ensure package manager repositories are configured | Get repositories"
      ansible.builtin.command: apt-cache policy
      changed_when: false
      failed_when: false
      check_mode: false
      register: ubtu20cis_1_2_1_2_apt_policy

    - name: "1.2.1.2 | AUDIT | Ensure package manager repositories are configured | Message out repository configs"
      ansible.builtin.debug:
        msg:
          - "Warning!!  Below are the apt package repositories"
          - "Please review to make sure they conform to your sites policies"
          - "{{ ubtu20cis_1_2_1_2_apt_policy.stdout_lines }}"

    - name: "1.2.1.2 | AUDIT | Ensure package manager repositories are configured | Warn Count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '1.2.1.2'

- name: "1.2.2.1 | PATCH | Ensure updates, patches, and additional security software are installed"
  when: ubtu20cis_rule_1_2_2_1
  tags:
    - level1-server
    - level1-workstation
    - manual
    - patch
    - rule_1.2.2.1
    - apt
  ansible.builtin.package:
    name: "*"
    state: latest
