---
- name: "1.8.1 | PATCH | Ensure GNOME Display Manager is removed"
  ansible.builtin.package:
      name: gdm3
      state: absent
  notify: change_requires_reboot
  when:
      - ubtu20cis_rule_1_8_1
      - not ubtu20cis_desktop_required
      - ubtu20cis_disruption_high
  tags:
      - level2-server
      - manual
      - patch
      - rule_1.8.1
      - gnome

- name: "1.8.2 | PATCH | Ensure GDM login banner is configured"
  ansible.builtin.lineinfile:
      path: /etc/gdm3/greeter.dconf-defaults
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: "{{ item.insertafter }}"
      create: true
      owner: root
      group: root
      mode: 0644
  notify: reload gdm
  with_items:
      - { regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]', insertafter: EOF }
      - { regexp: 'banner-message-enable', line: 'banner-message-enable=true', insertafter: '\[org\/gnome\/login-screen\]'}
      - { regexp: 'banner-message-text', line: "banner-message-text='{{ ubtu20cis_warning_banner | regex_replace('\n', ' ') | trim }}'", insertafter: 'banner-message-enable' }
  when:
      - ubtu20cis_rule_1_8_2
      - ubtu20cis_desktop_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.8.2
      - gnome

- name: "1.8.3 | PATCH | Ensure disable-user-list is enabled"
  ansible.builtin.lineinfile:
      path: /etc/gdm3/greeter.dconf-defaul
      regexp: '^disable-user-list='
      line: 'disable-user-list=true'
      insertafter: 'banner-message-text='
      create: true
      owner: root
      group: root
      mode: 0644
  notify: reload gdm
  when:
      - ubtu20cis_rule_1_8_3
      - ubtu20cis_desktop_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.8.3
      - gdm3

- name: "1.8.4 | PATCH | Ensure XDCMP is not enabled"
  ansible.builtin.lineinfile:
      path: /etc/gdm3/custom.conf
      regexp: '^Enable.*=.*true'
      state: absent
  when:
      - ubtu20cis_rule_1_8_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.8.4
      - xdcmp
