---

- name: "1.1.9 | PATCH | Disable Automounting"
  ansible.builtin.service:
      name: autofs
      state: stopped
      enabled: false
  when:
      - ubtu20cis_rule_1_1_9
      - ubtu20cis_autofs_service_status.stdout == "loaded"
      - not ubtu20cis_allow_autofs
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.9
      - automounting
