---
- name: "4.4 | PATCH | Ensure logrotate assigns appropriate permissions"
  block:
      - name: "4.4 | AUDIT | Ensure logrotate assigns appropriate permissions | find logrotate create files"
        ansible.builtin.find:
            paths: /etc/logrotate.d/
            contains: '^\s*create\s\s*(?!0[6][0,4]0)(([0-9]|)[0-9]{3})'
            use_regex: true
        register: ubtu20cis_rule_4_4_logrotate_create

      - name: "4.4 | PATCH | Ensure logrotate assigns appropriate permissions | update logrotate.d files if exists"
        ansible.builtin.lineinfile:
            path: "{{ item.path }}"
            regexp: '^(\s*\b)create($|\s)(\d*)(\b.*)$'
            line: '\g<1>create {{ ubtu20cis_logrotate_create_settings }}\g<4>'
            backrefs: true
            insertbefore: '^}'
        with_items:
            - { path: '/etc/logrotate.conf'}
            - "{{ ubtu20cis_rule_4_4_logrotate_create.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - ubtu20cis_rule_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.4
      - logrotate
