---

- name: "4.2.1 | PATCH | Ensure ufw is installed"
  when:
    - ubtu20cis_rule_4_2_1
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.2.1
    - apt
    - ufw
  ansible.builtin.package:
    name: ufw
    state: present

- name: "4.2.2 | PATCH | Ensure nftables is not in use with ufw"
  when: ubtu20cis_rule_4_2_2
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.2.2
  block:
    - name: "4.2.2 | AUDIT | Ensure nftables is not in use with ufw | check status"
      ansible.builtin.debug:
        msg: "This control requires manual remediation"

    - name: "4.2.2 | AUDIT | Ensure nftables is not in use with ufw | Warn Count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '4.2.2'

- name: "4.2.3 | PATCH | Ensure iptables-persistent is not installed with ufw"
  when:
    - ubtu20cis_rule_4_2_3
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.2.3
    - ufw
  # Adding the allow OpenSSH rule while enabling ufw to allow ansible to run after enabling
  ansible.builtin.package:
    name: iptables-persistent
    state: absent

- name: "4.2.4 | PATCH | Ensure ufw service is enabled"
  when:
    - ubtu20cis_rule_4_2_4
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.2.4
    - ufw
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled

- name: "4.2.5 | PATCH | Ensure ufw loopback traffic is configured"
  when:
    - ubtu20cis_rule_4_2_5
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.2.5
    - ufw
  block:
    - name: "4.2.5 | PATCH | Ensure ufw loopback traffic is configured | Set allow in ufw rules"
      community.general.ufw:
        rule: allow
        direction: in
        interface: lo
      notify: Reload ufw

    - name: "4.2.5 | PATCH | Ensure ufw loopback traffic is configured | Set allow out ufw rules"
      community.general.ufw:
        rule: allow
        direction: out
        interface: lo
      notify: Reload ufw

    - name: "4.2.5 | PATCH | Ensure ufw loopback traffic is configured | Set deny ufw rules IPv4"
      community.general.ufw:
        rule: deny
        direction: in
        from_ip: 127.0.0.0/8
      notify: Reload ufw

    - name: "4.2.5 | PATCH | Ensure ufw loopback traffic is configured | Set deny ufw rules IPv6"
      when: ubtu20cis_ipv6_required
      community.general.ufw:
        rule: deny
        direction: in
        from_ip: "::1"
      notify: Reload ufw

- name: "4.2.6 | PATCH | Ensure ufw outbound connections are configured"
  when:
    - ubtu20cis_rule_4_2_6
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - manual
    - patch
    - rule_4.2.6
    - ufw
  block:
    - name: "4.2.6 | PATCH | Ensure ufw outbound connections are configured | Custom ports"
      when: ubtu20cis_ufw_allow_out_ports != "all"
      community.general.ufw:
        rule: allow
        direction: out
        to_port: '{{ item }}'
      with_items:
        - "{{ ubtu20cis_ufw_allow_out_ports }}"
      notify: Reload ufw

    - name: "4.2.6 | PATCH | Ensure ufw outbound connections are configured | Allow all"
      when: "'all' in ubtu20cis_ufw_allow_out_ports"
      community.general.ufw:
        rule: allow
        direction: out
      notify: Reload ufw

- name: "4.2.7 | AUDIT | Ensure ufw firewall rules exist for all open ports"
  when:
    - ubtu20cis_rule_4_2_7
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - manual
    - audit
    - rule_4.2.7
    - ufw
  block:
    - name: "4.2.7 | AUDIT | Ensure ufw firewall rules exist for all open ports | Get list of open ports"
      ansible.builtin.command: ss -4tuln
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_ufw_open_listen_ports

    - name: "4.2.7 | AUDIT | Ensure ufw firewall rules exist for all open ports | Get list of firewall rules"
      ansible.builtin.command: ufw status
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_ufw_firewall_rules

    - name: "4.2.7 | AUDIT | Ensure ufw firewall rules exist for all open ports | Message out settings"
      ansible.builtin.debug:
        msg:
          - "Warning!! Below are the listening ports and firewall rules"
          - "Please create firewall rule for any open ports if not already done"
          - "*****---Open Listen Ports---*****"
          - "{{ discovered_ufw_open_listen_ports.stdout_lines }}"
          - "*****---Firewall Rules---*****"
          - "{{ discovered_ufw_firewall_rules.stdout_lines }}"

    - name: "4.2.7 | AUDIT | Ensure ufw firewall rules exist for all open ports | Warn Count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '4.2.7'

- name: "OPTIONAL | UFW incoming ports"
  when: ufw_add_incoming
  tags:
    - ufw
    - ufw_in_ports
  community.general.ufw:
    rule: allow
    direction: in
    from_ip: '{{ item.from }}'
    to_port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  loop: "{{ ubtu20cis_ufw_allow_in }}"
  loop_control:
    label: "{{ item.port }}"
  notify: Reload ufw

- name: "4.2.8 | PATCH | Ensure ufw default deny firewall policy"
  when:
    - ubtu20cis_rule_4_2_8
    - ubtu20cis_firewall_package == "ufw"
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.2.8
    - ufw
  community.general.ufw:
    default: deny
    direction: "{{ item }}"
  with_items:
    - incoming
    - outgoing
    - routed
  notify: Reload ufw
