---

- name: "4.1.1 | PATCH | Ensure a single firewall configuration utility is in use"
  when: ubtu20cis_rule_4_1_1
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_4.1.1
    - ufw
  ansible.builtin.package:
    name: ufw
    state: present
