---
- name: "AUTOMATED | 4.1.2.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ ubtu20cis_max_log_file_size }}"
      state: present
  notify: restart auditd
  when:
      - ubtu20cis_rule_4_1_2_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.2.1
      - auditd

- name: "AUTOMATED | 4.1.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^max_log_file_action'
      line: "max_log_file_action = {{ ubtu20cis_auditd['max_log_file_action'] }}"
  notify: restart auditd
  when:
      - ubtu20cis_rule_4_1_2_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.2.2
      - auditd

- name: "AUTOMATED | 4.1.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
      - { regexp: '^space_left_action', line: 'space_left_action = email' }
      - { regexp: '^action_mail_acct', line: 'action_mail_acct = root' }
      - { regexp: '^admin_space_left_action', line: 'admin_space_left_action = halt' }
  notify: restart auditd
  when:
      - ubtu20cis_rule_4_1_2_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.2.3
      - auditd
