---
- name: "4.2.3 | PATCH | Ensure permissions on all logfiles are configured"
  block:
      - name: "4.2.3 | AUDIT | Ensure permissions on all logfiles are configured | discover "
        ansible.builtin.shell: find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d
        changed_when: false
        check_mode: false
        register: ubtu20cis_4_2_3_logfile_perms_status

      - name: "4.2.3 | PATCH | Ensure permissions on all logfiles are configured | adjust "
        ansible.builtin.shell: find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec chmod g-w,o-rwx "{}" +
        check_mode: false
        when:
            - ubtu20cis_4_2_3_logfile_perms_status.stdout | length > 0
  when:
      - ubtu20cis_rule_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.3
      - logfiles
      - permissions
