---

- name: "SECTION | 4.1 | Configure single firewall utility"
  ansible.builtin.import_tasks:
    file: cis_4.1.x.yml

- name: "SECTION | 4.2 | Configure UFW"
  ansible.builtin.import_tasks:
    file: cis_4.2.x.yml

- name: "SECTION | 4.3 | Configure nftables"
  ansible.builtin.import_tasks:
    file: cis_4.3.x.yml

- name: "SECTION | 4.4 | Configure iptables"
  ansible.builtin.import_tasks:
    file: cis_4.4.x.yml
